### PR TITLE
Bootstrap styling added (draft PR)

### PR DESCRIPTION
**Pull request by clyde-johnston**
The Bootstrap CSS styling of all the UAVCAN website components is ready for review at the [UAT](http://uat.uavcan.org) website. Per the requirements, I have included:
- The UAVCAN color scheme (see /static/css/color-scheme.css)
- The "Recent Posts" and "Recent Development" feeds in their own column on larger viewports
- A carousel slideshow of the selected images
- Responsive scaling for mobile and desktop browsers

Some changes that may be needed before merging include:
- Content -- no changes have been made to the content pending new content
- Fixed title / sidebar -- these currently scroll off the screen when scrolling through the content

Please review and comment on the changes and any further changes that may be required.

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
Thanks, Clyde, and sorry that it took me a week to get back to this. We are still working on the legal docs for the Consortium; they should be completed and published synchronously with this website, hopefully before the end of this month (meaning in 2 weeks).

Soon I will be rewriting the introductory description shown on the front page; I suppose the best way to go about that would be to create a separate doc, proofread it with your help, and then copy-paste it into HTML.

Regarding the current changeset, I have a few suggestions.

- [x] Tweak the layout a bit. The current arrangement looks okay on my workstation, but when I test it using my tiny 13" laptop, I see this:

  image

  The screen real estate appears to be utilized inefficiently. I suggest we move the logo from the top of the page to the very top of the left column and let the carousel occupy the center-top; likewise, the right column would be shifted upwards:

  path837-7-5

  The shift makes the beginning of the text appear on the page at the initial scroll position:

  image (1)

  ***Edit:*** it would also be nice to move the footer (where the link "Contribute to this website on GitHub" is) to the left sidebar, too, unless there is not enough space or you consider it to be a poor design choice. The motivation is to make the GitHub link more discoverable and to make the page appear smaller (a long page might hamper user engagement, I suspect).

- [ ] ~~It is great that we are now using the UAVCAN palette, but the application of its colors seems a little questionable. I suggest we cut down on the colors a bit and go closer to the original black-and-whiteish design. The blue links and the green section headers on the right side seem out of place.~~ (see #15)

- [ ] ~~Upon some consideration I am inclined to prefer having the logos moved to the Consortium page to illustrate membership. We could perhaps use the right column for that. Likewise, logos of equipment vendors could be used to somehow illustrate the Conformant Products section, but I don't have any practical ideas about this yet.~~ (see #15)

- [x] On a sufficiently wide screen the link icons appear so distant from their links they seem almost unrelated:

  image

  Maybe they should switch to the other side, or their relation should be somehow highlighted.

- [x] We will not be able to use the image of the Futaba servo. Please use this one instead:

  hitecrc

- [x] I seem to recall that you suggested earlier that links to external resources (Spec, Forum, etc) should be separated from the website navigation links. Let's do that. At least some of these links will be page-specific; for instance, the Consortium page will link the bylaws and the application form; there is no point having these on the front page. Not sure what's the best way to arrange this.

- [x] The images on the carousel need to be annotated. I am not sure about the design but the intended content is a single brief sentence outlining the present applications of UAVCAN: manned and unmanned vehicles, spacecraft, robotic systems, COTS equipment, etc. Also, the navigation arrows seem to have disappeared from the carousel.

--- *added later:* ---

- [x] Can we please have ToC like this on the home page also?

  image

**Comment by pavel-kirienko** [comment]
Regarding https://github.com/UAVCAN/uavcan.org/pull/15#issuecomment-732960572, the most obvious solution is to disable hyphenation in menus, or add a style `hyphenated` or something and apply it selectively to the main content and the side cards (hyphenation is essential for the cards). Can you do that?

**Comment by clyde-johnston** [comment]
We are ready for another review. I have removed the jumbotron header and replaced it with a horizontal navbar. Sidebar navigation is now for second-level navigation and is hidden on smaller viewports. Scrollspy and hover functionality has been added to the sidebar navigation to improve visualization of current location.

I have also created a new `uat` branch which is dedicated to the code pushed to [UAT](http://uat.uavcan.org). The working branch is still `bootstrap`. You can merge the working branch into `uat` when you are ready to push to UAT.

**Comment by clyde-johnston** [comment]
I have added the "UAVCAN Guide" as an HTML page, and improved the presentation of the sidebar menu. There is still some formatting work to be done on the Guide but the content is all there.

**Comment by clyde-johnston** [comment]
Formatting the 'UAVCAN Guide' is complete. This site is ready to merge with `master` pending any further changes you may want.

**Comment by clyde-johnston** [comment]
Requested changes per Slack:
- [x] Move navigation menu to the sidebar

- [x] Make header background white

- [x] Move adopter logos to the Consortium page

- [x] Remove space between header and carousel on smaller single-column viewport

- [x] Hyperlink Guide navigation to UAVCAN forum

**Comment by clyde-johnston** [comment]
I will close this PR and open a new one to pull the `uat` branch into `master` now that we have a dedicated `uat` branch.

**Pull request closed without merging**
